baseURL = 'https://twarga.github.io'
languageCode = 'en-us'
title = 'Twarga Blog - Computer Science & Cyber Security Insights'
theme = "m10c"
googleAnalytics = "GTM-NP9V3HC4"

[params]
  author = "Younes Touzani (Twarga)"
  description = "Explore Computer Science, Cyber Security, DevSecOps, and programming tutorials. Follow my learning path and project documentation in tech."

  [params.seo]
    title = "Twarga Blog | CS, Cyber Security & Tech Tutorials by Younes Touzani"
    description = "Dive into Computer Science, Cyber Security, DevSecOps, and programming insights. Join Younes Touzani (Twarga) on a learning journey through tutorials, lessons, and real-world tech projects."
    keywords = ["Computer Science", "Cyber Security", "DevSecOps", "programming", "tech tutorials", "project documentation", "Younes Touzani", "Twarga", "CS student", "learning path", "tech blog"]

  [[params.social]]
    icon = 'github'
    name = "Github"
    url = "https://github.com/Twarga"

  [[params.social]]
    icon = 'twitter'
    name = 'Twitter'
    url = "https://x.com/Twarga_Dev"

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
